org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
neo_version=21.11.42

mod_id=castle_in_the_sky
mod_name=Castle in the Sky
mod_license=MIT
mod_version=1.21.11.1
mod_group_id=com.song.castle_in_the_sky
mod_authors=CarrotOfRivia
mod_description=Castle in the Sky, ported to Minecraft 1.21.11.
