license="MIT"

[[mods]]
modId="castle_in_the_sky"
version="26.1.2.1"
displayName="Castle in the Sky"
description='''
Castle in the Sky
'''

[[dependencies.castle_in_the_sky]]
modId="neoforge"
type="required"
versionRange="[26.1.2.59-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.castle_in_the_sky]]
modId="minecraft"
type="required"
versionRange="[26.1.2]"
ordering="NONE"
side="BOTH"
